from __future__ import annotations

from typing import Dict, List


SCIENCE_CONCEPTS: List[Dict[str, str]] = [
    {"topic": "Photoelectric effect", "family": "Quantum", "equation": "K_max = h f - phi", "prompt": "Explain threshold frequency with red vs blue light."},
    {"topic": "Wave superposition", "family": "Waves", "equation": "y = y1 + y2", "prompt": "Show constructive, destructive, and partial interference."},
    {"topic": "Single-slit diffraction", "family": "Optics", "equation": "a sin theta = m lambda", "prompt": "Animate a wavefront spreading through one slit."},
    {"topic": "Double-slit interference", "family": "Quantum", "equation": "d sin theta = m lambda", "prompt": "Show two paths producing bright and dark fringes."},
    {"topic": "Pendulum energy exchange", "family": "Mechanics", "equation": "E = K + U", "prompt": "Show energy trading between height and speed."},
    {"topic": "Relativity light cone", "family": "Spacetime", "equation": "c^2 t^2 - x^2", "prompt": "Show allowed causal paths inside a light cone."},
    {"topic": "Prism spectrum", "family": "Optics", "equation": "n(lambda)", "prompt": "Show white light dispersing into wavelengths."},
    {"topic": "Polarization", "family": "Optics", "equation": "I = I0 cos^2(theta)", "prompt": "Show an electric field filtered by a polarizer."},
    {"topic": "Newton's second law", "family": "Mechanics", "equation": "F = m a", "prompt": "Show force changing acceleration for two masses."},
    {"topic": "Conservation of momentum", "family": "Mechanics", "equation": "p_i = p_f", "prompt": "Show two carts colliding and exchanging momentum."},
    {"topic": "Hooke's law", "family": "Mechanics", "equation": "F = -k x", "prompt": "Animate a spring restoring force."},
    {"topic": "Simple harmonic motion", "family": "Mechanics", "equation": "x = A cos(omega t)", "prompt": "Connect circular motion to oscillation."},
    {"topic": "Doppler effect", "family": "Waves", "equation": "f' = f (v +/- vo)/(v -/+ vs)", "prompt": "Show compressed and stretched wavefronts."},
    {"topic": "Standing waves", "family": "Waves", "equation": "L = n lambda / 2", "prompt": "Show nodes and antinodes on a string."},
    {"topic": "Resonance", "family": "Waves", "equation": "f = f0", "prompt": "Show amplitude growing near natural frequency."},
    {"topic": "Snell's law", "family": "Optics", "equation": "n1 sin theta1 = n2 sin theta2", "prompt": "Show a ray bending across media."},
    {"topic": "Total internal reflection", "family": "Optics", "equation": "sin theta_c = n2/n1", "prompt": "Show the critical angle and reflection."},
    {"topic": "Lens equation", "family": "Optics", "equation": "1/f = 1/do + 1/di", "prompt": "Show object, lens, image, and focal points."},
    {"topic": "Electric field lines", "family": "Electromagnetism", "equation": "E = F/q", "prompt": "Show field direction around charges."},
    {"topic": "Coulomb's law", "family": "Electromagnetism", "equation": "F = k q1 q2 / r^2", "prompt": "Show force changing with distance."},
    {"topic": "Gauss's law", "family": "Electromagnetism", "equation": "Phi_E = Q/epsilon0", "prompt": "Show flux through a closed surface."},
    {"topic": "Magnetic force", "family": "Electromagnetism", "equation": "F = q v x B", "prompt": "Show a charged particle curving in a magnetic field."},
    {"topic": "Faraday induction", "family": "Electromagnetism", "equation": "emf = -dPhi_B/dt", "prompt": "Show changing flux inducing current."},
    {"topic": "RC circuit charging", "family": "Circuits", "equation": "V = V0(1 - e^{-t/RC})", "prompt": "Show capacitor voltage rising over time."},
    {"topic": "AC phase", "family": "Circuits", "equation": "V = V0 sin(omega t)", "prompt": "Show voltage and current phase offset."},
    {"topic": "Blackbody radiation", "family": "Quantum", "equation": "lambda_max T = b", "prompt": "Show spectrum shifting with temperature."},
    {"topic": "Bohr energy levels", "family": "Quantum", "equation": "Delta E = h f", "prompt": "Show electron transitions emitting photons."},
    {"topic": "Uncertainty principle", "family": "Quantum", "equation": "Delta x Delta p >= hbar/2", "prompt": "Show narrow position creating broad momentum."},
    {"topic": "Quantum tunneling", "family": "Quantum", "equation": "T > 0", "prompt": "Show a wavefunction crossing a barrier."},
    {"topic": "Radioactive decay", "family": "Nuclear", "equation": "N = N0 e^{-lambda t}", "prompt": "Show nuclei decaying over half-lives."},
    {"topic": "Half-life", "family": "Nuclear", "equation": "N = N0 / 2^n", "prompt": "Show quantity halving each interval."},
    {"topic": "Binding energy", "family": "Nuclear", "equation": "E = Delta m c^2", "prompt": "Show mass defect becoming energy."},
    {"topic": "Gravitational potential", "family": "Gravity", "equation": "U = -G M m / r", "prompt": "Show potential well around a mass."},
    {"topic": "Orbital velocity", "family": "Gravity", "equation": "v = sqrt(GM/r)", "prompt": "Show stable orbit speed vs radius."},
    {"topic": "Escape velocity", "family": "Gravity", "equation": "v_e = sqrt(2GM/r)", "prompt": "Show the threshold to leave a planet."},
    {"topic": "Kepler's third law", "family": "Gravity", "equation": "T^2 proportional a^3", "prompt": "Compare inner and outer orbital periods."},
    {"topic": "Center of mass", "family": "Mechanics", "equation": "R = sum m_i r_i / sum m_i", "prompt": "Show balance point shifting with masses."},
    {"topic": "Torque", "family": "Mechanics", "equation": "tau = r x F", "prompt": "Show lever arm changing rotation."},
    {"topic": "Angular momentum", "family": "Mechanics", "equation": "L = I omega", "prompt": "Show spin speeding up when radius shrinks."},
    {"topic": "Bernoulli principle", "family": "Fluids", "equation": "P + 1/2 rho v^2 + rho g h = const", "prompt": "Show pressure dropping where speed rises."},
    {"topic": "Buoyancy", "family": "Fluids", "equation": "F_b = rho V g", "prompt": "Show displaced fluid producing upward force."},
    {"topic": "Viscosity", "family": "Fluids", "equation": "F = eta A dv/dy", "prompt": "Show layers sliding with resistance."},
    {"topic": "Heat conduction", "family": "Thermodynamics", "equation": "q = -k grad T", "prompt": "Show heat flowing down a temperature gradient."},
    {"topic": "Entropy", "family": "Thermodynamics", "equation": "Delta S >= 0", "prompt": "Show ordered particles becoming dispersed."},
    {"topic": "Ideal gas law", "family": "Thermodynamics", "equation": "PV = nRT", "prompt": "Show pressure, volume, and temperature tradeoffs."},
    {"topic": "Carnot cycle", "family": "Thermodynamics", "equation": "eta = 1 - Tc/Th", "prompt": "Show four engine stages on a PV diagram."},
    {"topic": "Specific heat", "family": "Thermodynamics", "equation": "Q = m c Delta T", "prompt": "Show different materials warming at different rates."},
    {"topic": "Phase change", "family": "Thermodynamics", "equation": "Q = m L", "prompt": "Show temperature plateau during melting."},
    {"topic": "Logistic growth", "family": "Biology", "equation": "dN/dt = rN(1 - N/K)", "prompt": "Show population approaching carrying capacity."},
    {"topic": "Natural selection", "family": "Biology", "equation": "fitness -> frequency", "prompt": "Show traits becoming common over generations."},
    {"topic": "Enzyme kinetics", "family": "Biochemistry", "equation": "v = Vmax[S]/(Km + [S])", "prompt": "Show saturation curve as substrate increases."},
    {"topic": "DNA replication", "family": "Biology", "equation": "A-T, C-G", "prompt": "Show strands separating and copying."},
    {"topic": "Protein folding", "family": "Biochemistry", "equation": "minimize free energy", "prompt": "Show chain collapsing into stable shape."},
    {"topic": "Action potential", "family": "Neuroscience", "equation": "V_m(t)", "prompt": "Show depolarization and repolarization wave."},
    {"topic": "Photosynthesis", "family": "Biology", "equation": "CO2 + H2O -> glucose + O2", "prompt": "Show light energy converted into chemical energy."},
    {"topic": "Cell membrane diffusion", "family": "Biology", "equation": "J = -D grad C", "prompt": "Show particles moving down concentration gradient."},
    {"topic": "Osmosis", "family": "Biology", "equation": "water -> higher solute", "prompt": "Show water crossing a semipermeable membrane."},
    {"topic": "pH scale", "family": "Chemistry", "equation": "pH = -log[H+]", "prompt": "Show acidity changing logarithmically."},
    {"topic": "Chemical equilibrium", "family": "Chemistry", "equation": "K = products/reactants", "prompt": "Show forward and reverse rates balancing."},
    {"topic": "Le Chatelier principle", "family": "Chemistry", "equation": "system shifts", "prompt": "Show equilibrium responding to a stress."},
    {"topic": "Reaction rate", "family": "Chemistry", "equation": "rate = k[A]^n", "prompt": "Show concentration changing collision rate."},
    {"topic": "Activation energy", "family": "Chemistry", "equation": "k = A e^{-Ea/RT}", "prompt": "Show catalyst lowering the energy barrier."},
    {"topic": "Molecular orbitals", "family": "Chemistry", "equation": "bonding vs antibonding", "prompt": "Show orbitals combining into energy levels."},
    {"topic": "Ionic bonding", "family": "Chemistry", "equation": "electron transfer", "prompt": "Show electron transfer creating attraction."},
    {"topic": "Covalent bonding", "family": "Chemistry", "equation": "shared electrons", "prompt": "Show atoms sharing electron density."},
    {"topic": "Titration curve", "family": "Chemistry", "equation": "equivalence point", "prompt": "Show pH jump near equivalence."},
    {"topic": "Buffer solution", "family": "Chemistry", "equation": "pH = pKa + log(A-/HA)", "prompt": "Show buffer resisting pH change."},
    {"topic": "Plate tectonics", "family": "Earth Science", "equation": "mantle convection", "prompt": "Show plates moving over convection cells."},
    {"topic": "Seismic waves", "family": "Earth Science", "equation": "P and S waves", "prompt": "Show wave types traveling through Earth."},
    {"topic": "Greenhouse effect", "family": "Climate", "equation": "radiative balance", "prompt": "Show incoming visible and outgoing infrared radiation."},
    {"topic": "Carbon cycle", "family": "Climate", "equation": "reservoir exchange", "prompt": "Show carbon moving through atmosphere, ocean, life, rock."},
    {"topic": "Ocean currents", "family": "Climate", "equation": "density + wind", "prompt": "Show warm and cold currents circulating."},
    {"topic": "Cloud formation", "family": "Atmosphere", "equation": "condensation", "prompt": "Show air rising, cooling, and condensing."},
    {"topic": "Projectile motion", "family": "Mechanics", "equation": "x = vt, y = y0 + v_y t - 1/2 g t^2", "prompt": "Show horizontal and vertical motion independently."},
    {"topic": "Inclined plane", "family": "Mechanics", "equation": "mg sin theta", "prompt": "Resolve gravity into components along a ramp."},
    {"topic": "Friction", "family": "Mechanics", "equation": "f <= mu N", "prompt": "Show static and kinetic friction thresholds."},
    {"topic": "Work energy theorem", "family": "Mechanics", "equation": "W = Delta K", "prompt": "Show force over distance changing kinetic energy."},
    {"topic": "Power", "family": "Mechanics", "equation": "P = W/t", "prompt": "Compare same work done at different rates."},
    {"topic": "Vector decomposition", "family": "Math", "equation": "v = vx i + vy j", "prompt": "Show a vector split into components."},
    {"topic": "Dot product", "family": "Math", "equation": "a dot b = |a||b| cos theta", "prompt": "Show projection and alignment."},
    {"topic": "Cross product", "family": "Math", "equation": "|a x b| = |a||b| sin theta", "prompt": "Show area and perpendicular direction."},
    {"topic": "Gradient", "family": "Math", "equation": "grad f", "prompt": "Show steepest ascent on a surface."},
    {"topic": "Divergence", "family": "Math", "equation": "div F", "prompt": "Show source and sink behavior in a vector field."},
    {"topic": "Curl", "family": "Math", "equation": "curl F", "prompt": "Show local rotation in a vector field."},
    {"topic": "Fourier series", "family": "Math", "equation": "sum a_n cos nx + b_n sin nx", "prompt": "Build a square wave from sine waves."},
    {"topic": "Convolution", "family": "Math", "equation": "(f * g)(t)", "prompt": "Slide one signal over another and accumulate overlap."},
    {"topic": "Bayes theorem", "family": "Statistics", "equation": "P(A|B)=P(B|A)P(A)/P(B)", "prompt": "Update belief after evidence."},
    {"topic": "Normal distribution", "family": "Statistics", "equation": "N(mu, sigma)", "prompt": "Show spread changing with standard deviation."},
    {"topic": "Central limit theorem", "family": "Statistics", "equation": "sample means -> normal", "prompt": "Show averages becoming bell-shaped."},
    {"topic": "Regression line", "family": "Statistics", "equation": "y = mx + b", "prompt": "Fit a line to noisy data."},
    {"topic": "Gradient descent", "family": "AI", "equation": "theta <- theta - eta grad L", "prompt": "Show steps downhill on a loss surface."},
    {"topic": "Neural network layer", "family": "AI", "equation": "y = sigma(Wx + b)", "prompt": "Show inputs transforming through weighted nodes."},
    {"topic": "Attention mechanism", "family": "AI", "equation": "softmax(QK^T/sqrt(d))V", "prompt": "Show tokens weighting other tokens."},
    {"topic": "Backpropagation", "family": "AI", "equation": "chain rule", "prompt": "Show error flowing backward through layers."},
    {"topic": "Information entropy", "family": "Information", "equation": "H = -sum p log p", "prompt": "Show uncertainty changing with probability distribution."},
    {"topic": "Compression", "family": "Information", "equation": "short codes for common symbols", "prompt": "Show frequent symbols getting shorter codes."},
    {"topic": "Error correction", "family": "Information", "equation": "redundancy detects noise", "prompt": "Show parity bits detecting a flip."},
    {"topic": "Epidemic SIR model", "family": "Systems", "equation": "S -> I -> R", "prompt": "Show susceptible, infected, recovered compartments."},
    {"topic": "Feedback loop", "family": "Systems", "equation": "output affects input", "prompt": "Show reinforcing and balancing loops."},
    {"topic": "Chaos sensitivity", "family": "Systems", "equation": "small delta grows", "prompt": "Show nearby initial conditions diverging."},
    {"topic": "Logarithmic scale", "family": "Math", "equation": "equal ratios, equal spacing", "prompt": "Show huge ranges compressed into readable spacing."},
    {"topic": "Exponential growth", "family": "Math", "equation": "N = N0 e^{rt}", "prompt": "Show constant percentage growth accelerating."},
    {"topic": "Inverse square law", "family": "Physics", "equation": "I proportional 1/r^2", "prompt": "Show intensity spreading over larger spheres."},
    {"topic": "Beat frequency", "family": "Waves", "equation": "f_beat = |f1 - f2|", "prompt": "Show two close tones creating amplitude beats."},
]
