from __future__ import annotations

TEMPLATES = [
    {
        "id": "science-explainer",
        "name": "Science Explainer",
        "category": "Education",
        "description": "Hook → experiment → explanation → equation → takeaway. Clean, clear, and persuasive.",
        "example_prompt": "Explain the photoelectric effect in 60 seconds.",
        "director_brief": "Start with a vivid hook, show a simple experiment, compare cases, then reveal the equation and recap.",
        "defaults": {
            "audience": "high school",
            "tone": "epic",
            "style": "cinematic",
            "pace": "medium",
            "color_palette": "cool",
            "include_equations": True,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 60,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
    {
        "id": "concept-to-intuition",
        "name": "Concept → Intuition",
        "category": "Education",
        "description": "Build intuition step-by-step with metaphors and clean visuals.",
        "example_prompt": "Explain backpropagation like I'm 16.",
        "director_brief": "Use a metaphor first, then map to the formal concept, end with a concise recap.",
        "defaults": {
            "audience": "high school",
            "tone": "calm",
            "style": "clean",
            "pace": "slow",
            "color_palette": "warm",
            "include_equations": False,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 75,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
    {
        "id": "experiment-compare",
        "name": "Experiment Compare",
        "category": "Physics",
        "description": "Show two setups side-by-side, compare outcomes, then explain why.",
        "example_prompt": "Compare red vs blue light in the photoelectric effect.",
        "director_brief": "Split screen comparison, emphasize cause/effect, end with key rule.",
        "defaults": {
            "audience": "undergrad",
            "tone": "serious",
            "style": "cinematic",
            "pace": "medium",
            "color_palette": "cool",
            "include_equations": True,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 50,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
    {
        "id": "math-derivation",
        "name": "Math Derivation",
        "category": "Math",
        "description": "Equation-first walkthrough with clean steps and visual checkpoints.",
        "example_prompt": "Derive the area of a circle in 90 seconds.",
        "director_brief": "Start with the equation, show transformations, use diagrams, end with result.",
        "defaults": {
            "audience": "undergrad",
            "tone": "serious",
            "style": "chalkboard",
            "pace": "medium",
            "color_palette": "monochrome",
            "include_equations": True,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 90,
            "aspect_ratio": "16:9",
            "quality": "pqm",
        },
    },
    {
        "id": "myth-vs-fact",
        "name": "Myth vs Fact",
        "category": "Science",
        "description": "Debunk a misconception with a clear visual test and conclusion.",
        "example_prompt": "Debunk the idea that heavier objects fall faster.",
        "director_brief": "Open with the myth, show experiment, then explain the correct idea.",
        "defaults": {
            "audience": "general",
            "tone": "playful",
            "style": "clean",
            "pace": "medium",
            "color_palette": "warm",
            "include_equations": False,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 45,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
    {
        "id": "timeline-evolution",
        "name": "Timeline Evolution",
        "category": "Biology",
        "description": "Story over time with stages and transitions.",
        "example_prompt": "Show how a star evolves from nebula to supernova.",
        "director_brief": "Use a timeline line, each stage with its own vignette and label.",
        "defaults": {
            "audience": "general",
            "tone": "epic",
            "style": "cinematic",
            "pace": "medium",
            "color_palette": "neon",
            "include_equations": False,
            "include_graphs": False,
            "include_narration": True,
            "target_seconds": 75,
            "aspect_ratio": "16:9",
            "quality": "pqh",
        },
    },
    {
        "id": "process-pipeline",
        "name": "Process Pipeline",
        "category": "AI",
        "description": "Show a system pipeline with inputs, transformations, and outputs.",
        "example_prompt": "Explain how a neural network classifies images.",
        "director_brief": "Use arrows, boxes, and a clear flow; end with example output.",
        "defaults": {
            "audience": "general",
            "tone": "epic",
            "style": "clean",
            "pace": "fast",
            "color_palette": "cool",
            "include_equations": False,
            "include_graphs": False,
            "include_narration": True,
            "target_seconds": 40,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
    {
        "id": "storyteller",
        "name": "Science Storyteller",
        "category": "Storytelling",
        "description": "Narrative-driven explainer with character/scene beats.",
        "example_prompt": "Tell the story of how vaccines train the immune system.",
        "director_brief": "Use a character (cell/antibody), introduce conflict, show resolution, recap.",
        "defaults": {
            "audience": "general",
            "tone": "epic",
            "style": "cinematic",
            "pace": "medium",
            "color_palette": "warm",
            "include_equations": False,
            "include_graphs": False,
            "include_narration": True,
            "target_seconds": 70,
            "aspect_ratio": "16:9",
            "quality": "pqm",
        },
    },
    {
        "id": "graph-first",
        "name": "Graph-First",
        "category": "Data",
        "description": "Start with a graph, zoom into intuition, then formalize.",
        "example_prompt": "Explain exponential growth with a graph.",
        "director_brief": "Graph first, annotate trend, then connect to equation and real-world effect.",
        "defaults": {
            "audience": "general",
            "tone": "serious",
            "style": "clean",
            "pace": "medium",
            "color_palette": "cool",
            "include_equations": True,
            "include_graphs": True,
            "include_narration": True,
            "target_seconds": 45,
            "aspect_ratio": "9:16",
            "quality": "pqm",
        },
    },
]
